name: Auto Label and Assign

on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Label based on files changed
        uses: actions/labeler@v5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/labeler.yml

      - name: Auto assign reviewers
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/auto-assign.yml
